### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by Qrysto** [monperrus/crawler-user-agents#14]
This list is is great and I want to use it in my project, but it would be easier to use if it's published to npm. Would you mind publishing this to npm?

**Comment by monperrus** [comment]
Feel free to do so. --Martin

**Comment by Qrysto** [comment]
Well, I could do the publishing but it'll be better if you the author publish it so that you can update it to npm when there're changes :)

**Comment by monperrus** [comment]
I won't do it for sake of time. I let the issue open for others to jump on.

**Comment by neurolabs** [comment]
@Qrysto Voight-Kampff has an (maybe) adequate solution for this. They have a build target that downloads a current version of the json file. See https://github.com/biola/Voight-Kampff/blob/f5c21ed0d99f7c42645bfd313aafebe2097cb9e8/lib/tasks/voight_kampff.rake. This way they don't need a published dependency.

**Comment by UltCombo** [comment]
Hello guys, please take a look at #47, it may be what you are looking for. 😄

**Comment by monperrus** [comment]
Closing this one thanks to #47.

To be installed with NPM: `npm install "https://github.com/monperrus/crawler-user-agents.git"`

**Comment by UltCombo** [comment]
I think I forgot to add the explanation. 😅

I've sent a PR to make the package `require()`able in Node.js and updated the usage instructions as well, please take a look when you can: #88.
