### ISSUE TITLE
update version on NPM

### ISSUE THREAD

**Issue by f0rmat1k** [monperrus/crawler-user-agents#148]
Good day!

NPM version was published 3 years ago: https://www.npmjs.com/package/crawler-user-agents
And package.json that version doesn't contain "main": "crawler-user-agents.json".

**Comment by monperrus** [comment]
@shumkov could you give me the rights to push a new version on npmjs: https://www.npmjs.com/package/crawler-user-agents

My NPM login is also `monperrus`.

Thanks!

**Comment by shumkov** [comment]
@monperrus Sure, done.

**Comment by monperrus** [comment]
Thanks a lot. Just released the latest version.

We should have a new release for each commit on master: https://github.com/monperrus/crawler-user-agents/commit/a9c68a6f2826551808eedf3b0c37dfaa46f046e4
