### ISSUE TITLE
Why is "Googlebot" not recognized without trailing slash?

### ISSUE THREAD

**Issue by egilburg** [monperrus/crawler-user-agents#22]
https://support.google.com/webmasters/answer/182072 says `Googlebot` is used as user agent for the default web crawler.

But https://github.com/monperrus/crawler-user-agents/blob/master/crawler-user-agents.json#L3 only recognizes `Googlebot/` with trailing slash.

Thanks.

**Comment by monperrus** [comment]
to differentiate the "main" Googlebot  from Googlebot-Mobile, Googlebot-Image, Googlebot-Video, etc.
