### ISSUE TITLE
Code-friendly license

### ISSUE THREAD

**Issue by lxg** [monperrus/crawler-user-agents#23]
I respect every developer’s right to pick their own license, but have you considered using a more code-friendly license?

Unfortunately, CC licenses are problematic for code, as they are more targeted at artwork and their definitions of „sharing“ and „mixing“ are ambiguous in the context of code.

My suggestion would be to switch to either the MIT or the LGPL license. MIT is rather permissive and very common these days, LGPL is more similar to CC-BY-SA.

**Comment by monperrus** [comment]
> Unfortunately, CC licenses are problematic for code, as they are more targeted at artwork and their definitions of „sharing“ and „mixing“ are ambiguous in the context of code.

Do you recommend a pointer to a page explaining those problems?

Thanks. --Martin

**Comment by lxg** [comment]
Sure, CC themselves say so:

> We recommend against using Creative Commons licenses for software. Instead, we strongly encourage you to use one of the very good software licenses which are already available. We recommend considering licenses made available by the Free Software Foundation or listed as “open source” by the Open Source Initiative.
>[…]

https://creativecommons.org/faq/#can-i-apply-a-creative-commons-license-to-software

**Comment by monperrus** [comment]
Interesting. Is a JSON file  "software", "data" or "document"? Has anybody ever think about this?
