### ISSUE TITLE
Add centurybot9

### ISSUE THREAD

**Issue by thatcher** [monperrus/crawler-user-agents#266]
https://udger.com/resources/ua-list/bot-detail?bot=centurybot9

Used to be picked up as a Go-Http-Client, but now the agent we are seeing is: 

Mozilla/5.0 (compatible; +centuryb.o.t9[at]gmail.com)

Probably worth calling out into its own category as "Centurybot9" or something.  Thank you for this great project!

**Comment by monperrus** [comment]
Thanks, would you do a pull-request?
