### ISSUE TITLE
Adding new version of existing bot entry

### ISSUE THREAD

**Issue by jbuote** [monperrus/crawler-user-agents#293]
I've found that I'm getting "Python-requests/2.26.0" passing the check for bots.
Clearly, this version is not in the instances object array for the python-requests pattern.

Is adding version 2.26.0 something that should also be PR'd if I would like to request it get added?
I know to PR if a NEW pattern is found that isn't in the json already.
Just unclear on adding a version to an already existing pattern in your repository.

Apologies if this seems like a silly question, just trying to do it right. 😁 
Thanks!

**Comment by monperrus** [comment]
>  Just unclear on adding a version to an already existing pattern in your repository.

Adding new instances with new versions in a PR is welcome! Thanks.
