### ISSUE TITLE
Add linespider

### ISSUE THREAD

**Issue by Almenon** [monperrus/crawler-user-agents#310]
See https://help2.line.me/linesearchbot/web/?contentId=50006055&lang=en

> 1.  Linespider is a Web crawler managed by LINE. The user agents are as follows :
⋅Mozilla/5.0 (compatible; Linespider/1.1; +https://lin.ee/4dwXkTH)
⋅Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; Linespider/1.1; +https://lin.ee/4dwXkTH) Chrome/W.X.Y.Z Safari/537.36
The user agent string "W.X.Y.Z" contains the version number of the browser used by the user agent.

**Comment by monperrus** [comment]
Would you do propose it as a pull-request @Almenon ?

**Comment by monperrus** [comment]
ping @Almenon
