### ISSUE TITLE
Please also register this on packagist.org to use it via Composer

### ISSUE THREAD

**Issue by vanushwashere** [monperrus/crawler-user-agents#312]

**Comment by vanushwashere** [comment]
#313

**Comment by vanushwashere** [comment]
But you need to register at packagist.org and submit the application

**Comment by vanushwashere** [comment]
Hey, I fixed the path in this MR
https://github.com/monperrus/crawler-user-agents/pull/315

**Comment by monperrus** [comment]
done, see https://packagist.org/packages/monperrus/crawler-user-agents
