### ISSUE TITLE
Voyager crawler

### ISSUE THREAD

**Issue by jpavello** [monperrus/crawler-user-agents#35]
I am using Voight-Kampf gem to identify wether a visit is a crawler and I recently noticed several non-bot requests detected as robots. They all match with the voyager crawler, corresponding to kosmix.com (a website that doesn't seem to be online anynore) but they do because the user agent includes the string "VOYAGER2 DG310" which happens to be a smartphone by Doogee.

I think this value should probably either be removed (as the site seems to be offline) or be changed to "voyager ", adding a blank space at the end of the string, but I'm not sure which option is the best solution and thats why I open a issue instead a PR.

**Comment by monperrus** [comment]
> I think this value should probably either be removed

Sounds a good idea, thanks.
