### ISSUE TITLE
is_crawler in python is case sensitive now.

### ISSUE THREAD

**Issue by jurasans** [monperrus/crawler-user-agents#381]
In a project I work on, the crawler detection makes the user-agent string uniform by lowercasing the user-agent string before passing into the crawler detection.

In the past this worked fine, but now after the sep 6 commit (and subsequent release) we started having issues with the detection of crawlers.

THIS BREAK BACKWARDS COMPATIBILITY

**Comment by monperrus** [comment]
fixed by https://github.com/monperrus/crawler-user-agents/pull/382
