### ISSUE TITLE
Problem with AdsBot-Google user agent

### ISSUE THREAD

**Issue by vetyy** [monperrus/crawler-user-agents#54]
Hello,

I was using your awesome list to filter out some robots traffic, but recently results got worse than before, I found out it is because of change on AdsBot-Google user agent. It stopped matching mobile version of AdsBot-Google-Mobile (https://support.google.com/adwords/answer/2404197).

Would it be possible to just change "AdsBot-Google(?!-)" back to "AdsBot-Google"?

I think all user agents that contains AdsBot-Google.*, now or in future, are bots, so it is probably more robust to use is that way.

Something nice to have: I am also using re2 library to match user agents (https://github.com/google/re2) but such regex is not supported in re2 and it must fallback to original re lib which is bit slower, so it would be wonderful to be able to stay compatible with re2.

```
  {
    "pattern": "AdsBot-Google(?!-)",
    "url": "https://support.google.com/webmasters/answer/1061943?hl=en"
  },
  {
    "pattern": "AdsBot-Google-Mobile-Apps",
    "addition_date": "2017/08/08",
    "url": "https://support.google.com/webmasters/answer/1061943?hl=en"
},
```

**Comment by monperrus** [comment]
Thanks for reporting the issue. What would be a re2 compatible pattern? Could you see how to integrate a re2 check in validate.py?

**Comment by vetyy** [comment]
Hey,

I have created pull request for re2 validation check.

If you want the original regex to match the same thing as it is right now and it should be compatible with re2, I believe this is fine: "AdsBot-Google(?!-)" == "AdsBot-Google([^-]|$)"

But then we should not forget to add "AdsBot-Google-Mobile" user agent to the list.

I can create pull request for that too, just tell me what do you prefer to have multiple regexes or just one that is general.

**Comment by vetyy** [comment]
PRs are ready for you.

**Comment by monperrus** [comment]
Thanks a lot, it seems we're done. This was also an opportunity to improve the validation script.
