### ISSUE TITLE
New bot names to add

### ISSUE THREAD

**Issue by fallax** [monperrus/crawler-user-agents#67]
The following have appeared in my logs recently and could be added:

- TelegramBot
- Discordbot 
- DuckDuckGo-Favicons-Bot 
- Ocarinabot 
- Cliqzbot 
- epicbot 
- SEMrushBot 
- Primalbot 
- GnowitNewsbot 
- Primalbot 
- Leikibot 
- LinkArchiver 
- linkfluence 
- PaperLiBot 
- infegy.com 
- Digg Deeper 
- dcrawl 
- Snacktory 
- AndersPinkBot 
- Fyrebot 
- EveryoneSocialBot 
- LivelapBot

Hope this is helpful!

**Comment by monperrus** [comment]
Thanks! Would you make a PR with the corresponding patterns in the JSON file? (maybe for the most
common ones only)

**Comment by fallax** [comment]
Will try and do this in the next week or two

**Comment by monperrus** [comment]
closed per #69
