### ISSUE TITLE
Some missing bot UAs

### ISSUE THREAD

**Issue by cmantas** [monperrus/crawler-user-agents#68]
Hello.
Good Job on this collection.
Here are some UAs we have found in our website logs that seem to be bots and the current version does not include:

* Done all, see below

The ones that are now handled (removed from the above list for sake of clarity):

* <s>IAS crawler (ias_crawler; http://integralads.com/site-indexing-policy/)</s>
* <s>SBL-BOT (http://sbl.net)</s>
* <s>Mozilla/5.0 (compatible; seoscanners.net/1; +spider@seoscanners.net)</s>
* <s>Mozilla/5.0 (compatible; oBot/2.3.1; +http://filterdb.iss.net/crawler/)</s>
* <s>Mozilla/5.0 (compatible; TinEye-bot/1.31; +http://www.tineye.com/crawler.html)</s>
* <s>LCC (+http://corpora.informatik.uni-leipzig.de/crawler_faq.html)</s>
* <s>ArchiveTeam ArchiveBot/20170106.02 (wpull 2.0.2)</s>
* <s>ICC-Crawler/2.0 (Mozilla-compatible; ; http://ucri.nict.go.jp/en/icccrawler.html)</s>
* <s>Mozilla/5.0 (compatible; Konqueror/3.5; Linux) KHTML/3.5.5 (like Gecko) (Exabot-Thumbnails)</s>
* <s>Mozilla/5.0 (compatible; Baiduspider-render/2.0; +http://www.baidu.com/search/spider.html), Mozilla/5.0 (iPhone; CPU iPhone OS 9_1 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13B143 Safari/601.1 (compatible; Baiduspider-render/2.0; +http://www.baidu.com/search/spider.html)
</s>

Not kept:

* <s>WordChampBot</s> confidential, not active, seems dead (see http://www.wordchamp.com)
* <s>Mozilla/5.0 (compatible; Flinkhubbot/1.1; +hello@flinkhub.com )</s> not active anymore

**Comment by monperrus** [comment]
Would you do a pull-request to add the most important missing ones for you?

**Comment by monperrus** [comment]
The ones that are now handled (removed from the initial post for sake of clarity):

* <s>ICC-Crawler/2.0 (Mozilla-compatible; ; http://ucri.nict.go.jp/en/icccrawler.html)</s>
* <s>Mozilla/5.0 (compatible; Konqueror/3.5; Linux) KHTML/3.5.5 (like Gecko) (Exabot-Thumbnails)</s>
* <s>Mozilla/5.0 (compatible; Baiduspider-render/2.0; +http://www.baidu.com/search/spider.html), Mozilla/5.0 (iPhone; CPU iPhone OS 9_1 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13B143 Safari/601.1 (compatible; Baiduspider-render/2.0; +http://www.baidu.com/search/spider.html)
</s>

**Comment by tekool** [comment]
Could you please add Slack Bots as described here: https://api.slack.com/robots

- Slackbot-LinkExpanding 1.0 (+https://api.slack.com/robots)
- Slack-ImgProxy 0.19 (+https://api.slack.com/robots)
- Slackbot 1.0(+https://api.slack.com/robots)

Thank you!

**Comment by zilkerfinancial** [comment]
This is a relatively new (but invasive) one, I will try to generate a pull request unless someone suggests a consolidation with another bot. They reportedly have four (https://udger.com/resources/ua-list/bot-detail?bot=Siteimprove.com%20bot) , but all seem to match
  {
    "pattern": "improve.com",
    "addition_date": "2018/06/22",
    "instances": [
      "Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.1; Trident/6.0) LinkCheck by Siteimprove.com",
      "Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.0) Match by Siteimprove.com",
      "Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.1; Trident/6.0) SiteCheck-sitecrawl by Siteimprove.com",
      "Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.0) LinkCheck by Siteimprove.com"
    ]
  },

**Comment by monperrus** [comment]
Thanks added Siteimprove.com in 69609980960199825d06b9212d80bb70b70dce2a

**Comment by monperrus** [comment]
Closing this issue, thanks for the suggestions!
