### ISSUE TITLE
Some user agents have incorrect capitalisation

### ISSUE THREAD

**Issue by fallax** [monperrus/crawler-user-agents#70]
Some user agents do not have the correct capitalisation and are currently all lowercase.

In particular:

- AhrefsBot
- Baiduspider
- Wget

This means they are not matching when used with "grep -f" and I would assume would be breaking with other regex engines also.

**Comment by monperrus** [comment]
you're right. would you fix these in a pull-request? thanks!

**Comment by fallax** [comment]
Looking at the file I think there's some additional incorrect entries not in my PR, based on the "instances" entries for those patterns:

- blekkobot (Blekkobot)
- buzzbot (Buzzbot/1.0)
- convera (ConveraCrawler/0.9e)
- dotbot (DotBot)
- exabot (Exabot PyExalead/3.0)
- findxbot (Findxbot/1.0)
- lipperhey (Lipperhey Link Explorer)
- mlbot (MLBot)
- page2rss (Page2RSS/0.7)
- postrank (PostRank/2.0)
- nutch (Nutch)
- seekbot (Seekbot/1.0)
- seznambot (SeznamBot/3.2-test1-1)
- slurp (Yahoo! Slurp)
- smtbot (SMTBot/1.0)
- speedy (Speedy Spider)
- summify (Summify/1.0.1)
- urlappendbot (URLAppendBot/1.0)
- voilabot (VoilaBot)
- wotbox (Wotbox/2.0)
- xovibot (XoviBot/2.0)

**Comment by fallax** [comment]
There may be further errors, those are just the ones I can find easily by looking at the "instances" field. I do wonder whether making "instances" a required field for new contributions might be a good idea - it'd allow more automated checking for stuff like this.

**Comment by fallax** [comment]
I just realised, you've got that already, it just doesn't run automatically

**Comment by fallax** [comment]
OK, I understand what is happening here now: they aren't matching the bot name, but they do match correctly against the *URL* in the user agent.

e.g. "lipperhey" matches "Mozilla/5.0 (compatible; Lipperhey-Kaus-Australis/5.0; +https://www.lipperhey.com/en/about/)" because it is found in the URL at the end.

This is why it is passing validate.py.

I think my PR is probably OK to go then.
