### ISSUE TITLE
Add pattern for Facebook app prefetching

### ISSUE THREAD

**Issue by fallax** [monperrus/crawler-user-agents#73]
Not sure if this is something that crawler-user-agents should be covering or not.

I have found that I can identify requests coming from the Facebook app that are *pre-fetches* of the page (i.e. not genuine visits) using this pattern:

FBRV/[0-9][0-9]

Genuine requests from the Facebook IAB instead have

FBRV/0

I have, however, not been able to find this documented anywhere, so this may possibly not continue to be the case in future.

If this is something that would make sense to include in crawler-user-agents I can make a PR for it - otherwise mark this wontfix!

**Comment by monperrus** [comment]
Those requests are initiated by users?

**Comment by fallax** [comment]
*Sort of* initiated by users, hence why I'm not sure whether it fits in crawler-user-agents or not.

If I understand it correctly, when a link to a site appears in a users' News Feed in the Facebook app, the app will often download the HTML of that page ahead of time, *before* the user interacts with the link in any way, and regardless of whether the user actually ever clicks on a link to the site. "FBRV/[0-9][0-9]" seems to only show these requests. They can be easily spotted by eye because UAs containing "FBRV/[0-9][0-9]" only ever request one HTML page and never any CSS, images etc linked from that page.

I'm not sure if that counts as "initiated by users" or not. Up to you.

**Comment by monperrus** [comment]
This is a grey area, but I would not count it as a "robot" request.

Thanks for the proposal!
