### ISSUE TITLE
Add links to language specific libraries and alternative databases in the README file

### ISSUE THREAD

**Issue by fallax** [monperrus/crawler-user-agents#76]
Other projects on GitHub provide language specific front-ends to crawler-user-agents, which people visiting the GitHub page for this project may not know about:

- https://github.com/biola/Voight-Kampff (Ruby)
- https://github.com/Hentioe/isbot (Ruby)

I suggest the README should list both of these so that people can find them easily.

This project is also one of a number of different projects on GitHub with databases of crawlers. Other projects may be more suitable to their needs than this one.

I've listed some other projects that allow people to identify crawlers by user agent below. These are the projects I can find that have good quality, comprehensive databases, and which seem to be being actively maintained. Others obviously exist but these appear to be the good quality ones.

- https://github.com/gorangajic/isbot (Node.JS)
- https://github.com/JayBizzle/Crawler-Detect (PHP)
- https://github.com/mimmi20/BrowserDetector (PHP)
- https://github.com/browscap/browscap (has extremely extensive JSON database of UAs including a crawlers section)

I'd suggest that these would also be useful additions to the README.

**Comment by monperrus** [comment]
I agree with you, that would be useful.

Could you propose a pull request?

Thanks!
