### ISSUE TITLE
AddThis

### ISSUE THREAD

**Issue by GurneyHallack** [monperrus/crawler-user-agents#8]
HTTP_USER_AGENT : AddThis.com robot tech.support@clearspring.com
https://www.webmasterworld.com/search_engine_spiders/3876346.htm

{
    "pattern": "AddThis",
    "url": "https://www.addthis.com",
    "instances": ["AddThis.com robot tech.support@clearspring.com"],
    "addition_date": "2015/06/02"
  }

**Comment by monperrus** [comment]
Good! Can you create the corresponding pull request?

Best, --Martin

**Comment by GurneyHallack** [comment]
Of course. 

However,  i'm busy for the moment so this will take some time ;) (i have other patterns to add).
