### ISSUE TITLE
How to Install in Apache?

### ISSUE THREAD

**Issue by PauloBoaventura** [monperrus/crawler-user-agents#86]
I know my question is beginner ...
But I really liked the project and I want to use it correctly ...

And my doubts are these:

1 - How to install correctly on a shared host.
2 - how to configure the folders that I do not want to be scanned.
3 - What should we replace in files and this extension is placed in a separate folder?
4 - Is there any robots for only images, like twitter and pinterest these are in the list?

Thank you for your attention!
And congratulations it's what I was looking for ...

**Comment by monperrus** [comment]
Nope, this repo is not for what you want.

You seem to look for https://support.google.com/webmasters/answer/6062596?hl=en
