### ISSUE TITLE
JSON syntax issues

### ISSUE THREAD

**Issue by plbowers** [monperrus/crawler-user-agents#89]
When I use json.lint your json syntax is fine, but when I try to use it on WAMP (PHP 5.6) I get syntax errors. I narrowed it down to the line

    "pattern": "Mediapartners \\(Googlebot\\)",

(I hope the backslashes will show in this comment)

I changed it to this and it worked fine:

    "pattern": "Mediapartners [(]Googlebot[)]",

Since your JSON is technically valid you may not want to bother "fixing" what isn't broken, but I thought I  would mention it here in case others run into the problem.

**Comment by monperrus** [comment]
could you make a PR for this? thanks!

**Comment by plbowers** [comment]
I'm not even sure it *should* be changed. Obviously what you have there is completely legal syntax for JSON and it's just some weird behavior of WAMP or PHP 5.6 or something. I just figured after going through the hassle of figuring out what was causing the problem I ought to document it somewhere...
