### ISSUE TITLE
Yandex Browser

### ISSUE THREAD

**Issue by alex-mashin** [monperrus/crawler-user-agents#9]
`  {
    "pattern": "yandex"
  }, `
is too wide. There is also Yandex.Browser.

Yandex's bot's signature includes `YandexBot`.

**Comment by monperrus** [comment]
Here is the number of requests for "yandex":
{{{
1 "mozilla/5.0 (compatible; yandeximageresizer/2.0; +http://yandex.com/bots)"
1 "mozilla/5.0 (compatible; yandexmedia/3.0; +http://yandex.com/bots)"
2 "mozilla/5.0 (compatible; yandexantivirus/2.0; +http://yandex.com/bots)"
2 "mozilla/5.0 (windows nt 5.1; rv:18.0) gecko/20100101 firefox/18.0 yandex.translate"
2 "mozilla/5.0 (windows nt 6.1; wow64; rv:13.0) gecko/20100101 firefox/13.0 yb/6.9 yandex.translate"
4 "mozilla/5.0 (compatible; yandexbot/3.0; mirrordetector; +http://yandex.com/bots)"
4 "mozilla/5.0 (x11; linux x86_64; rv:24.0) gecko/20140128 firefox/24.0 yandex.translate"
5 "mozilla/5.0 (compatible; yandeximages/3.0; +http://yandex.com/bots)"
9 "mozilla/5.0 (compatible; linux i686; yandex.gazeta bot/1.0; +http://gazeta.yandex.ru)"
49 "mozilla/5.0 (compatible; yandexdirect/3.0; +http://yandex.com/bots)"
1289 "yandex/1.01.001 (compatible; win16; i)"
8510 "mozilla/5.0 (compatible; yandexbot/3.0; +http://yandex.com/bots)"
}}}

"yandexbot" would miss "yandex/1.01.001 (compatible; win16; i)".

However, the last time I've seen "yandex/1.01.001 (compatible; win16; i)" is in June 2010. So let's go for yandexbot.
